name: Build and Deploy Jupyter Book to book/Intro2Bash

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # required for custom push token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter Book
        run: pip install -U jupyter-book

      - name: Build the Jupyter Book
        run: |
          jupyter-book build book/_sources
          rm -rf book/Intro2Bash
          mkdir -p book/Intro2Bash
          cp -r book/_sources/_build/html/* book/Intro2Bash/

      - name: Commit and Push Built Book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add book
          git commit -m "Update Jupyter Book" || echo "No changes to commit"
          git push